# Netlify configuration for React app deployment
# This will replace the current static site with the React app

[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# SPA routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API function redirects (keep existing)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variable templates (set in Netlify dashboard)
[template.environment]
  SUPABASE_URL = "Your Supabase project URL"
  SUPABASE_ANON_KEY = "Your Supabase anonymous key"
  SUPABASE_SERVICE_KEY = "Your Supabase service key (for functions)"
  OPENAI_API_KEY = "Your OpenAI API key"
  REPLICATE_API_TOKEN = "Your Replicate API token"
  PEXELS_API_KEY = "Your Pexels API key"
  STRIPE_PUBLIC_KEY = "Your Stripe publishable key"
  STRIPE_SECRET_KEY = "Your Stripe secret key"
  STRIPE_WEBHOOK_SECRET = "Your Stripe webhook secret"